;;; nael-lsp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from nael-lsp.el

(autoload 'nael-lsp-init "nael-lsp" "\
Prepare `lsp-mode' to work with `nael-mode'." t)
(register-definition-prefixes "nael-lsp" '("nael-lsp-"))


;;; End of scraped data

(provide 'nael-lsp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nael-lsp-autoloads.el ends here
