#!/usr/bin/env -S emacs -x
;; -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; SPDX-License-Identifier: GPL-3.0-only

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.

;;; Commentary:

;; This file is supposed to be run as Elisp script, e.g. from shell
;; via `./build.el'.  Its purpose is to generate other files,
;; depending on passed command-line arguments:

;; - Pass `abbreviations' to generate the Emacs-Lisp source files
;;   `nael/nael-abbrev.el' and `nael/nael-skeleton.el' based on data
;;   from the official Lean plugin for V. S. Code.
;; - Pass `autoloads' to generate `*/*-autoloads.el' files.
;; - Pass `compile' to generate `*/*.elc' files.  (This currenlty only
;;   succeeds for `nael' package.)
;; - Pass `info' to generate `nael/nael.info' and `nael/nael.texi'.
;; - Pass `root-readme' to copy `nael/README.org' to `./README.org'.

;; If no command-line arguments are passed, the following defaults
;; are targeted: `abbreviations', `info' and `root-readme'.

;;; Code:

(defconst build-targets
  (or command-line-args-left
      (list
       "abbreviations"
       ;; "autoloads"
       ;; "compile"
       "info"
       "root-readme")))

;;;; Build target `autoloads':

(when (member "autoloads" build-targets)
  (dolist (dir (file-expand-wildcards "nael*"))
    (loaddefs-generate
     dir
     (file-name-concat dir (concat dir "-autoloads.el")))))

;;;; Build target `compile':

;; TODO: Make dependencies `markdown-mode' and `lsp-mode' available.
(when (member "compile" build-targets)
  (dolist (dir (file-expand-wildcards "nael*"))
    (let ((load-path
           ;; Each package needs itself in `load-path'.  `nael-*'
           ;; packages each need `nael' in `load-path' too.
           (append (mapcar #'file-truename (list dir "nael"))
                   load-path))
          (dir (file-truename dir)))
      (byte-recompile-directory dir 0 t))))

;;;; Build targets `info' and `root-readme':

(require 'ox-texinfo)

;; Avoid README.org~ file.
(setq backup-inhibited t)
(setq create-lockfiles nil)

(with-temp-buffer
  (find-file "nael/README.org")
  ;; On the Codeberg website <https://codeberg.org/mekeor/nael> the
  ;; table of contents doesn't look nice.  Gladly, Codeberg/Forgejo
  ;; respects the file-local setting “toc:nil”.  But for Texinfo
  ;; exports we do want a TOC, so here we remove that setting.
  (with-undo-amalgamate
    (replace-regexp (rx line-start "#+options: toc:nil" line-end) "")
    (when (member "info" build-targets)
      (org-texinfo-export-to-info)))
  (ignore-errors (undo))
  ;; We want a readme to be displayed on the website.  Unfortunately,
  ;; Codeberg/Forgejo does not render the README.org if it's a
  ;; symbolic link.  Hence, we just create a copy.  To avoid
  ;; misunderstandings, we insert a comment at top and force
  ;; read-only file-locally.
  (insert "# DO NOT EDIT THIS FILE!\n"
          "# IT IS JUST A BUILD-TIME COPY OF nael/README.org!\n"
          "# EDIT THE ORIGINAL FILE INSTEAD!\n\n")
  (add-file-local-variable 'buffer-read-only t)
  (when (member "root-readme" build-targets)
    (write-file "../README.org")))

;;;; Build target `abbreviations':

(defconst build-abbrev-alist
  (when (member "abbreviations" build-targets)
    ;; 1. Drop abbreviations that contain a space character so that
    ;;    regexps can be used to distinguish abbreviation-expanding
    ;;    character-insertions from abbreviation endings.  As of
    ;;    writing this, ("+ " . "⊹") is the only affected pair.
    ;; 2. Drop abbreviations that contain a backslash character so
    ;;    that adjacent backslash-prefixed abbreviations expand
    ;;    correctly typing \.\. SPC will yield ··.
    (seq-remove
     (lambda (pair) (string-match-p "[ \\]" (car pair)))
     (with-temp-buffer
       (url-insert-file-contents
        (concat "https://raw.githubusercontent.com"
                "/leanprover/vscode-lean4/refs/heads/master"
                "/lean4-unicode-input/src/abbreviations.json"))
       (goto-char (point-min))
       (let ((json-key-type 'string))
         (json-read)))))
  "Raw abbreviations alist mapping strings to strings.

Keys may include `$CURSOR'.")

(defconst build-abbrev-separator
  (regexp-quote "$CURSOR"))

(defconst build-abbrev-singletons
  (seq-remove (lambda (pair)
                (string-match-p build-abbrev-separator (cdr pair)))
              build-abbrev-alist))

(defconst build-abbrev-skeletons
  (mapcan
   (pcase-lambda (`(,abbrev . ,expans))
     (when-let*
         ((expans (string-split expans build-abbrev-separator))
          ((not (length= expans 1))))
       (list (list abbrev (car expans) (cadr expans)
                   (concat "nael-skeleton-"
                           (mapconcat (apply-partially #'format "%x")
                                      abbrev))))))
   build-abbrev-alist))

(defconst build-abbrev-regexp-char
   ;; Workaround bug of `rx--string-to-intervals' at dashes.
   `(or ?- (any ,(string-replace
                  "-" "" (mapconcat #'car build-abbrev-alist)))))

(defconst build-abbrev-regexp-table
  (rx (group "\\" (one-or-more (eval build-abbrev-regexp-char)))))

;; For editing the strings that include Elisp code, it's best to
;; install the package `separedit', then type C-u M-x separedit-dwim
;; RET emacs-lisp-mode RET.

(when (member "abbreviations" build-targets)
  (with-temp-file "nael/nael-abbrev.el"
    (insert
     (format
      ";;; nael-abbrev.el --- Abbrev for Nael  -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; SPDX-License-Identifier: GPL-3.0-only

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.GPL3.

;;; Commentary:

;; This file has been generated by `build.el' by relying on data from
;; the official Lean plugin for another editor.  Please do not edit
;; this file directly; edit `build.el' instead!

;; This file defines Abbrev tables for conveniently inserting Unicode
;; characters that are common in Lean code.  For more information on
;; Emacs' Abbrev feature, consult the docstrings of `abbrev-mode' and
;; `local-abbrev-table' and the corresponding Info manual:
;;
;;   (info \"(emacs) Abbrevs\")

;; The abbreviations introduced here can be classified into two
;; disjunct sets:
;;
;;   1. /Singleton/ abbreviations expand to single strings.  During
;;      expansion, point is reserved at the end of expansion.
;;
;;   2. /Skeleton/ abbreviations expand to two strings with point
;;      being placed between the left and the right part.  The name is
;;      derived from `skeleton', a built-in Emacs package used to
;;      implement this class of abbreviations.
;;
;; As a consequence, this file defines three Abbrev tables.
;; `nael-abbrev-singleton-table' and `nael-abbrev-skeleton-table' have
;; self-explaining names.  The recommended Abbrev table for
;; `nael-mode' is `nael-abbrev-table' which inherits elements from
;; both aforementioned Abbrev tables.

;; One crucial challenge in the development of this file was that
;; `abbrev-mode' was originally designed for abbreviations that
;; exclusively consist of word-constituent characters.  Whereas in
;; Lean, we desire abbreviations like \\f<<>>.  One measure we need to
;; take for this requirement is to specify `:regexp' properties for
;; our Abbrev tables; see (info \"(elisp) Abbrev Table Properties\").
;; This already works fine when calling `expand-abbrev' explicitly.
;; But at the time of writing (August 2025), `self-insert-command'
;; rules out automatic expansion of abbreviations that end in
;; non-word-constituent characters.  As a workaround, you can call
;; function `nael-abbrev-configure'.  It will add `nael-abbrev-expand'
;; to the `post-self-insert-hook' which considers expansion for a
;; suitably wider range of characters.

;;; Code:

(require 'abbrev)
(require 'cl-lib)

(require 'nael-skeleton)

(defgroup nael-abbrev nil
  \"`abbrev-mode' configured for `nael-mode'.\"
  :group 'nael
  :group 'abbrev-mode
  :link '(emacs-library-link :tag \"Source Lisp File\" \"nael-abbrev.el\")
  :prefix \"nael-abbrev-\")

(defconst nael-abbrev-regexp %S)

(define-abbrev-table 'nael-abbrev-singleton-table
  %s
  \"Abbrev table with singleton abbreviations for `nael-mode'.

All abbreviations expand to single strings.  During expansion, point is
reserved at the end of expansion.\"
  :regexp nael-abbrev-regexp)

(define-abbrev-table 'nael-abbrev-skeleton-table
  %s
  \"Abbrev table with Skeleton abbreviations for `nael-mode'.

All abbreviations expand to two strings with point being placed between
the left and the right part.  The name is derived from `skeleton', a
built-in Emacs package used to implement this class of abbreviations.\"
  :regexp nael-abbrev-regexp)

(define-abbrev-table 'nael-abbrev-table
  nil
\"Abbrev table for `nael-mode'.

It includes both singleton abbreviations that expand to single strings,
as well as Skeleton abbreviations that expand to two strings, with point
being placed between the left and the right part.\"
  :regexp nael-abbrev-regexp
  :parents (list nael-abbrev-singleton-table
                 nael-abbrev-skeleton-table))

(defcustom nael-abbrev-configure-table nael-abbrev-table
  \"Abbrev table activated by `nael-abbrev-configure'.
When nil, no Abbrev table will be activated.\"
  :type '(choice (const :tag \"Do not activate any Abbrev table\" nil)
                 (sexp :tag \"Activate an Abbrev table\"))
  :options '( nael-abbrev-table
              nael-abbrev-singleton-table
              nael-abbrev-skeleton-table)
  :group 'nael-abbrev)

;;;; Completion at point function (CAPF):

(defcustom nael-abbrev-capf t
  \"Whether to set up function `nael-abbrev-capf' as CAPF buffer-locally.\"
  :type 'boolean
  :group 'nael-abbrev)

(defun nael-abbrev-capf-exit (_string status)
  \"Exit CAPF by expanding the abbrev unless completion might continue.

When STATUS is `exact', the user might continue the completion, so we
should not exit.\"
  (unless (eq status 'exact)
    (expand-abbrev)))

(defun nael-abbrev-capf-annotation (abbrev)
  \"Annotate ABBREV with its expansion.\"
  (truncate-string-to-width (abbrev-expansion abbrev) 30 0 nil t))

(defvar nael-abbrev-capf-properties
  (list :annotation-function #'nael-abbrev-capf-annotation
        :category 'nael-abbrev
        :exclusive 'no
        :exit-function #'nael-abbrev-capf-exit)
  \"Completion properties for function `nael-abbrev-capf'.

See `completion-at-point-functions'.\")

(defvar nael-abbrev-capf-cache nil
  \"Cache used to speed up function `nael-abbrev-capf'.\")

(defun nael-abbrev-capf-reset ()
  \"Wipe cache of function `nael-abbrev-capf'.

As a consequence, this forces recollection of abbreviations later on.\"
  (interactive)
  (setq nael-abbrev-capf-cache nil))

(defun nael-abbrev-table-ancestors (tables)
  \"List of TABLES and their recursive ancestors.\"
  (when tables
    (let (ancestors)
      (while-let ((table (pop tables)))
        (dolist (parent (cons table
                              (abbrev-table-get table :parents)))
          (cl-pushnew parent ancestors)))
      ancestors)))

(defun nael-abbrev-capf-collect ()
  \"From active Abbrev tables, collect all abbreviations.

Returns an obarray whose symbol names are abbreviations.

Since CAPFs should be cheap to compute, this uses a cache.  The keys is
just the list of active tables given per `abbrev--active-tables',
compared with `equal'.  This should be fine because Abbrev tables are
not expected to be modified frequently.  If needed, the cache can be
reset with `nael-abbrev-capf-reset'.\"
  (let ((tbls (abbrev--active-tables)))
    (or (alist-get tbls nael-abbrev-capf-cache nil nil #'equal)
        (setf (alist-get tbls nael-abbrev-capf-cache nil nil #'equal)
              (let ((abbrevs (obarray-make)))
                (dolist (tbl (nael-abbrev-table-ancestors tbls))
                  (mapatoms (lambda (abbrev)
                              (intern (symbol-name abbrev) abbrevs))
                            tbl))
                abbrevs)))))

(defun nael-abbrev-capf ()
  \"Complete Nael abbreviation at point.

If the text before point matches `nael-abbrev-regexp', provide
completion at point.\"
  (save-match-data
    (when (looking-back nael-abbrev-regexp (line-beginning-position))
      (append (list (match-beginning 0)
                    (match-end 0)
                    (nael-abbrev-capf-collect))
              nael-abbrev-capf-properties))))

;;;; Help at point:

(defface nael-abbrev-help-point '((t :box 1))
  \"Face of character where point would be positioned after expansion.\"
  :group 'nael-abbrev)

(defface nael-abbrev-help-abbrev '((t :inherit help-key-binding))
  \"Face of abbreviation.\"
  :group 'nael-abbrev)

(defun nael-abbrev-help-lookup (tables query)
  \"Accumulate pairs of abbrevs and expansions matching QUERY in TABLES.\"
  (let (matches)
    (dolist (table tables)
      (mapatoms
       (lambda (sym)
         (when-let*
             ((expansion
               (or (when-let* ((val (symbol-value sym))
                               ((equal query val)))
                     val)
                   (when-let* ((fun (symbol-function sym)))
                     (with-temp-buffer
                       (funcall fun)
                       (set-text-properties (point-min) (point-max)
                                            nil)
                       (when (member
                              query
                              (list (buffer-substring (point-min)
                                                      (point))
                                    (buffer-substring (point)
                                                      (point-max))
                                    (buffer-substring (point-min)
                                                      (point-max))))
                         (unless (eobp)
                           (put-text-property
                            (point) (1+ (point)) 'face
                            'nael-abbrev-help-point))
                         (buffer-substring (point-min)
                                           (point-max)))))))
              (abbrev (symbol-name sym))
              ((not (string-empty-p abbrev))))
           (push (cons (propertize abbrev
                                   'face 'nael-abbrev-help-abbrev)
                       expansion)
                 matches)))
       table))
    matches))

;;;###autoload
(defun nael-abbrev-help (&optional beg end)
  \"Echo abbreviations for region (from BEG to END) or character at point.

When region is usable (`use-region-p'), act on string in region.  When
there is a character after point, act on in it as string.

Reverse lookup this query string in all active abbrev
tables (`abbrev--active-tables') and echo all abbreviations with a
matching expansion.  For abbrevs based on functions, e.g. Skeletons, the
function will be called before matching the query against the resulting
expansion to the left of point, to its right, or the whole expansion.

This command is inspired by `quail-show-key'.\"
  (interactive)
  (if-let* ((noregion (not (use-region-p))) ((eobp)))
      (message \"No character after point and no usable region\")
    (if noregion
        (setq beg (point) end (1+ (point)))
      ;; Because (interactive \"r\") fails when no mark has ever been
      ;; set in the current buffer, we set the region bounds manually.
      (setq beg (region-beginning) end (region-end)))
    (if-let* ((query (buffer-substring-no-properties beg end))
              (tables (nael-abbrev-table-ancestors
                       (abbrev--active-tables)))
              (pairs (nael-abbrev-help-lookup tables query))
              (max (apply #'max (mapcar (lambda (pair)
                                          (string-width (car pair)))
                                        pairs))))
        (message (string-join
                  (mapcar (lambda (pair)
                            (concat (string-pad (car pair) max)
                                    \" abbreviates \" (cdr pair)))
                          pairs)
                  \"\n\"))
      (message \"No abbreviation known for `%%s'\"
               ;; Avoid newlines in echo area, when either character
               ;; at point is newline or multi-line region is active.
               (string-replace \"\n\" \"\\n\" query)))))

;;;; Expansion and Configuration:

(defun nael-abbrev-expand ()
  \"Expand symbol-including abbreviation before point.\"
  (and abbrev-mode
       (string-match-p %S
                       (char-to-string last-command-event))
       (let ((pt (point))) (backward-char)
            (unless (expand-abbrev)
              (goto-char pt)))))

;;;###autoload
(defun nael-abbrev-configure ()
  \"Configure `abbrev-mode' for `nael-mode'.

Buffer-locally sets `local-abbrev-table' to
`nael-abbrev-configure-table' and adds `nael-abbrev-expand' to
`post-self-insert-hook' so that symbol-including abbreviations are
expanded whenever suitable characters are inserted.\"
  (when nael-abbrev-table
    (setq-local local-abbrev-table nael-abbrev-table))
  (add-hook 'post-self-insert-hook
            #'nael-abbrev-expand nil 'local)
  (when nael-abbrev-capf
    (add-hook 'completion-at-point-functions
              #'nael-abbrev-capf nil 'local)))

(provide 'nael-abbrev)

;;; nael-abbrev.el ends here

;; %s:
;; buffer-read-only: t
;; End:
"
      build-abbrev-regexp-table
      (let ((max (1- (length build-abbrev-singletons))))
        (string-join
         (seq-map-indexed
          (lambda (pair index)
            (format "%s%S %S nil :system t%s"
                    (if (eq 0 index) "'((" "    (")
                    (concat "\\" (car pair))
                    (cdr pair)
                    (if (eq max index) "))" ")")))
          build-abbrev-singletons)
         "\n"))
      (let ((max (1- (length build-abbrev-skeletons))))
        (string-join
         (seq-map-indexed
          (pcase-lambda (`(,abbrev ,expl ,expr ,name) index)
            (format "%s%S \"\" %s :system t%s"
                    (if (eq 0 index) "'((" "    (")
                    (concat "\\" abbrev)
                    name
                    (if (eq max index) "))" ")")))
          build-abbrev-skeletons)
         "\n"))
      (rx (not (eval build-abbrev-regexp-char)))
      "Local Variables"))))

(when (member "abbreviations" build-targets)
  (with-temp-file "nael/nael-skeleton.el"
    (insert
     (format
      ";;; nael-skeleton.el --- Skeleton for Nael  -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; SPDX-License-Identifier: GPL-3.0-only

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.GPL3.

;;; Commentary:

;; This file has been generated by `build.el' by relying on data from
;; the official Lean plugin for another editor.  Please do not edit
;; this file directly; edit `build.el' instead!

;; This file defines Skeleton templates for abbreviations that expand
;; to two strings, with point being placed between the left and the
;; right part.  For more information on Emacs' built-in `skeleton'
;; package, see consult its Info manual:
;;
;;   (info \"(autotype) Top\")

;; Note that `nael-abbrev' defines Abbrev tables built on top of these
;; Skeleton templates, as described at:
;;
;;   (info \"(autotype) Skeletons as Abbrevs\")

;;; Code:

(require 'skeleton)

%s

(provide 'nael-skeleton)

;;; nael-skeleton.el ends here

;; %s:
;; buffer-read-only: t
;; End:
"
      (let ((max (1- (length build-abbrev-skeletons))))
        (string-join
         (seq-map-indexed
          (pcase-lambda (`(,abbrev ,left ,right ,name) index)
            (format
             "(define-skeleton %s \"\" nil %S _ %S)"
             name left right))
          build-abbrev-skeletons)
         "\n"))
      "Local Variables"))))

;;; build ends here

;; Local Variables:
;; no-byte-compile: t
;; outline-regexp: "^;;;; Build target"
;; End:
