#!/usr/bin/env -S emacs -x
;; -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.

;;; Commentary:

;; This file generates Emacs-Lisp source files based on data from the
;; official Lean plugin for another editor.

;; For editing the strings that include Elisp code, it's best to
;; install the package `separedit', then type C-u M-x separedit-dwim
;; RET emacs-lisp-mode RET.

;;; Code:

;;;; Fetch Upstream Abbreviations

(defconst build-abbrev-alist
  (with-temp-buffer
    (url-insert-file-contents
     (concat "https://raw.githubusercontent.com"
             "/leanprover/vscode-lean4/refs/heads/master"
             "/lean4-unicode-input/src/abbreviations.json"))
    (goto-char (point-min))
    (let ((json-key-type 'string))
      (json-read)))
  "Raw abbreviations alist mapping strings to strings.

Keys may include `$CURSOR'.")

(defconst build-abbrev-separator
  (regexp-quote "$CURSOR"))

(defconst build-abbrev-singletons
  (seq-remove (lambda (pair)
                (string-match-p build-abbrev-separator (cdr pair)))
              build-abbrev-alist))

(defconst build-abbrev-skeletons
  (mapcan
   (pcase-lambda (`(,abbrev . ,expans))
     (when-let*
         ((expans (string-split expans build-abbrev-separator))
          ((not (length= expans 1))))
       (list (list abbrev (car expans) (cadr expans)
                   (concat "nael-skeleton-"
                           (mapconcat (apply-partially #'format "%x")
                                      abbrev))))))
   build-abbrev-alist))

(defconst build-abbrev-table-regexp
  ;; The regexp for characters that might be part of abbreviations, in
  ;; addition to word constituents, is "[][)(}{><|-]".  That's because
  ;; `]' has to be at the beginning, and `-' has to be at the end of
  ;; bracket expressions; see (info "(elisp) Regexp Special").
  "\\(\\\\[][)(}{><|[:word:]-]+\\)")

;;;; Generate `nael-abbrev.el'

(with-temp-file "nael/nael-abbrev.el"
  (insert
   (format
    ";;; nael-abbrev.el --- Abbrev for Nael  -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.GPL3.

;;; Commentary:

;; This file has been generated by `build.el' by relying on data from
;; the official Lean plugin for another editor.  Please do not edit
;; this file directly; edit `build.el' instead!

;; This file defines Abbrev tables for conveniently inserting Unicode
;; characters that are common in Lean code.  For more information on
;; Emacs' Abbrev feature, consult the docstrings of `abbrev-mode' and
;; `local-abbrev-table' and the corresponding Info manual:
;;
;;   (info \"(emacs) Abbrevs\")

;; The abbreviations introduced here can be classified into two
;; disjunct sets:
;;
;;   1. /Singleton/ abbreviations expand to single strings.  During
;;      expansion, point is reserved at the end of expansion.
;;
;;   2. /Skeleton/ abbreviations expand to two strings with point
;;      being placed between the left and the right part.  The name is
;;      derived from `skeleton', a built-in Emacs package used to
;;      implement this class of abbreviations.
;;
;; As a consequence, this file defines three Abbrev tables.
;; `nael-abbrev-table-only-singletons' and
;; `nael-abbrev-table-only-skeletons' have self-explaining names.  The
;; recommended Abbrev table for `nael-mode' is `nael-abbrev-table'
;; which inherits elements from both aforementioned Abbrev tables.

;; One crucial challenge in the development of this file was that
;; `abbrev-mode' was originally designed for abbreviations that
;; exclusively consist of word-constituent characters.  Whereas in
;; Lean, we desire abbreviations like \\f<<>>.  One measure we need to
;; take for this requirement is to specify `:regexp' properties for
;; our Abbrev tables; see (info \"(elisp) Abbrev Table Properties\").
;; This already works fine when calling `expand-abbrev' explicitly.
;; But at the time of writing (August 2025), `self-insert-command'
;; rules out automatic expansion of abbreviations that end in
;; non-word-constituent characters.  As a workaround, you can call
;; function `nael-abbrev-configure'.  It will add `nael-abbrev-expand'
;; to the `post-self-insert-hook' which considers expansion for a
;; suitably wider range of characters.

;;; Code:

(require 'abbrev)

(require 'nael-skeleton)

(defgroup nael-abbrev nil
  \"`abbrev-mode' configured for `nael-mode'.\"
  :group 'nael
  :group 'abbrev-mode
  :link '(emacs-library-link :tag \"Source Lisp File\" \"nael-abbrev.el\")
  :prefix \"nael-abbrev-\")

(defun nael-abbrev-expand ()
  \"Expand symbol-including abbreviation before point.\"
  (and abbrev-mode
       (string-match-p %S
                       (char-to-string last-command-event))
       (let ((pt (point))) (backward-char)
            (unless (expand-abbrev)
              (goto-char pt)))))

;;;###autoload
(defun nael-abbrev-configure ()
  \"Configure `abbrev-mode' for `nael-mode'.

Buffer-locally sets `local-abbrev-table' to
`nael-abbrev-configure-table' and adds `nael-abbrev-expand' to
`post-self-insert-hook' so that symbol-including abbreviations are
expanded whenever suitable characters are inserted.\"
  (when nael-abbrev-table
    (setq-local local-abbrev-table nael-abbrev-table))
  (add-hook 'post-self-insert-hook #'nael-abbrev-expand nil 'local))

(define-abbrev-table 'nael-abbrev-table-only-singletons
  %s
  \"Abbrev table with singleton abbreviations for `nael-mode'.

All abbreviations expand to single strings.  During expansion, point is
reserved at the end of expansion.\"
  :regexp %S)

(define-abbrev-table 'nael-abbrev-table-only-skeletons
  %s
  \"Abbrev table with Skeleton abbreviations for `nael-mode'.

All abbreviations expand to two strings with point being placed between
the left and the right part.  The name is derived from `skeleton', a
built-in Emacs package used to implement this class of abbreviations.\"
  :regexp %S)

(define-abbrev-table 'nael-abbrev-table
  nil
\"Abbrev table for `nael-mode'.

It includes both singleton abbreviations that expand to single strings,
as well as Skeleton abbreviations that expand to two strings, with point
being placed between the left and the right part.\"
  :regexp %S
  :parents (list nael-abbrev-table-only-singletons
                 nael-abbrev-table-only-skeletons))

(defcustom nael-abbrev-configure-table nael-abbrev-table
  \"Abbrev table activated by `nael-abbrev-configure'.
When nil, no Abbrev table will be activated.\"
  :type '(choice (const nil :tag \"Do not activate any Abbrev table\")
                 (sexp :tag \"Activate an Abbrev table\"))
  :options '( nael-abbrev-table
              nael-abbrev-table-only-singletons
              nael-abbrev-table-only-skeletons)
  :group 'nael-abbrev)

(defface nael-abbrev-help-point
  '((t :box 1))
  \"Face of character where point would be positioned after expansion.\"
  :group 'nael-abbrev)

(defface nael-abbrev-help-abbrev
  '((t :inherit help-key-binding))
  \"Face of abbreviation.\"
  :group 'nael-abbrev)

(defun nael-abbrev-help--lookup (query tables pairs)
  \"Accumulate PAIRS matching QUERY in TABLES.\"
  (if-let* ((table (pop tables)))
      (progn
        (mapatoms
         (lambda (sym)
           (when-let*
               ((expansion
                 (or (when-let* ((val (symbol-value sym))
                                 ((equal query val)))
                       val)
                     (when-let* ((fun (symbol-function sym)))
                       (with-temp-buffer
                         (funcall fun)
                         (set-text-properties (point-min) (point-max)
                                              nil)
                         (when (member
                                query
                                (list (buffer-substring
                                       (point-min) (point))
                                      (buffer-substring
                                       (point) (point-max))
                                      (buffer-substring
                                       (point-min) (point-max))))
                           (unless (eobp)
                             (put-text-property
                              (point) (1+ (point))
                              'face 'nael-abbrev-help-point))
                           (buffer-substring (point-min)
                                             (point-max)))))))
                (abbrev (symbol-name sym))
                ((not (string-empty-p abbrev))))
             (push (cons (propertize abbrev
                                     'face 'nael-abbrev-help-abbrev)
                         expansion)
                   pairs)))
         table)
        (nael-abbrev-help--lookup
         query (append (abbrev-table-get table :parents) tables)
         pairs))
    pairs))

;;;###autoload
(defun nael-abbrev-help (&optional beg end)
  \"Echo abbreviations for region (from BEG to END) or character at point.

When region is usable (`use-region-p'), act on string in region.  When
there is a character after point, act on in it as string.

Reverse lookup this query string in all active abbrev
tables (`abbrev--active-tables') and echo all abbreviations with a
matching expansion.  For abbrevs based on functions, e.g. Skeletons, the
function will be called before matching the query against the resulting
expansion to the left of point, to its right, or the whole expansion.

This command is inspired by `quail-show-key'.\"
  (interactive)
  (if-let* ((noregion (not (use-region-p))) ((eobp)))
      (message \"No character after point and no usable region\")
    (if noregion
        (setq beg (point) end (1+ (point)))
      ;; Because (interactive \"r\") fails when no mark has ever been
      ;; set in the current buffer, we set the region bounds manually.
      (setq beg (region-beginning) end (region-end)))
    (if-let* ((query (buffer-substring-no-properties beg end))
              (tables (abbrev--active-tables))
              (pairs (nael-abbrev-help--lookup query tables nil))
              (max (apply #'max (mapcar (lambda (pair)
                                          (string-width (car pair)))
                                        pairs))))
        (message (string-join
                  (mapcar (lambda (pair)
                            (format (concat \"%%-\"
                                            (number-to-string max)
                                            \"s abbreviates %%s\")
                                    (car pair)
                                    (cdr pair)))
                          pairs)
                  \"\\n\"))
      (message \"No abbreviation known for `%%s'\" query))))

(provide 'nael-abbrev)

;;; nael-abbrev.el ends here

;; %s:
;; buffer-read-only: t
;; End:
"
    "[^][)(}{><|[:word:]-]"
    (let ((max (1- (length build-abbrev-singletons))))
      (string-join
       (seq-map-indexed
        (lambda (pair index)
          (format "%s%S %S nil :system t%s"
                  (if (eq 0 index) "'((" "    (")
                  (concat "\\" (car pair))
                  (cdr pair)
                  (if (eq max index) "))" ")")))
        build-abbrev-singletons)
      "\n"))
    build-abbrev-table-regexp
    (let ((max (1- (length build-abbrev-skeletons))))
      (string-join
       (seq-map-indexed
        (pcase-lambda (`(,abbrev ,expl ,expr ,name) index)
          (format "%s%S \"\" %s :system t%s"
                  (if (eq 0 index) "'((" "    (")
                  (concat "\\" abbrev)
                  name
                  (if (eq max index) "))" ")")))
        build-abbrev-skeletons)
       "\n"))
    build-abbrev-table-regexp
    build-abbrev-table-regexp
    "Local Variables")))

;;;; Generate `neal-skeleton.el'

(with-temp-file "nael/nael-skeleton.el"
  (insert
   (format
    ";;; nael-skeleton.el --- Skeleton for Nael  -*- lexical-binding: t; -*-

;; Copyright © 2025 Mekeor Melire

;; This is licensed under GNU General Public License (version 3 only),
;; see LICENSE.GPL3.

;;; Commentary:

;; This file has been generated by `build.el' by relying on data from
;; the official Lean plugin for another editor.  Please do not edit
;; this file directly; edit `build.el' instead!

;; This file defines Skeleton templates for abbreviations that expand
;; to two strings, with point being placed between the left and the
;; right part.  For more information on Emacs' built-in `skeleton'
;; package, see consult its Info manual:
;;
;;   (info \"(autotype) Top\")

;; Note that `nael-abbrev' defines Abbrev tables built on top of these
;; Skeleton templates, as described at:
;;
;;   (info \"(autotype) Skeletons as Abbrevs\")

;;; Code:

(require 'skeleton)

%s

(provide 'nael-skeleton)

;;; nael-skeleton.el ends here

;; %s:
;; buffer-read-only: t
;; End:
"
    (let ((max (1- (length build-abbrev-skeletons))))
      (string-join
       (seq-map-indexed
        (pcase-lambda (`(,abbrev ,left ,right ,name) index)
          (format
           "(define-skeleton %s \"\" nil %S _ %S)"
           name left right))
        build-abbrev-skeletons)
       "\n"))
    "Local Variables")))

;;;; Generate `**/*-autoloads.el'

(dolist (dir (file-expand-wildcards "nael*"))
  (message dir)
  (loaddefs-generate
   dir
   (file-name-concat dir (concat dir "-autoloads.el"))))

;;;; Generate Texinfo and Info manuals and copy readme to repo-root

(require 'ox-texinfo)

;; Avoid README.org~ file.
(setq backup-inhibited t)
(setq create-lockfiles nil)

(with-temp-buffer
  (find-file "nael/README.org")
  ;; On the Codeberg website <https://codeberg.org/mekeor/nael> the
  ;; table of contents doesn't look nice.  Gladly, Codeberg/Forgejo
  ;; respects the file-local setting “toc:nil”.  But for Texinfo
  ;; exports we do want a TOC, so here we remove that setting.
  (with-undo-amalgamate
    (replace-regexp (rx line-start "#+options: toc:nil" line-end) "")
    (org-texinfo-export-to-info))
  (ignore-errors (undo))
  ;; We want a readme to be displayed on the website.  Unfortunately,
  ;; Codeberg/Forgejo does not render the README.org if it's a
  ;; symbolic link.  Hence, we just create a copy.  To avoid
  ;; misunderstandings, we insert a comment at top and force
  ;; read-only file-locally.
  (insert "# DO NOT EDIT THIS FILE!\n"
          "# IT IS JUST A BUILD-TIME COPY OF nael/README.org!\n"
          "# EDIT THE ORIGINAL FILE INSTEAD!\n\n")
  (add-file-local-variable 'buffer-read-only t)
  (write-file "../README.org"))

;;; build ends here
