\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename nael.info
@settitle Nael – A deprecated fork of Lean4-Mode
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@dircategory Emacs misc features
@direntry
* Nael: (nael).         Major mode for Lean.
@end direntry

@finalout
@titlepage
@title Nael – A deprecated fork of Lean4-Mode
@author Mekeor Melire
@end titlepage

@contents

@ifnottex
@node Top
@top Nael – A deprecated fork of Lean4-Mode

Nael was a fork of Lean4-Mode.  It has been deprecated in favor of
development on Lean4-Mode itself.

@end ifnottex

@menu
* Changelog::

@detailmenu
--- The Detailed Node Listing ---

Changelog

* Version 0.3.0 @emph{<2024-11-19 Tue>}: Version 030 @emph{<2024-11-19 Tue>}. 
* Version 0.2.2 released on @emph{<2024-07-05 Fri>}: Version 022 released on @emph{<2024-07-05 Fri>}. 

@end detailmenu
@end menu

@node Changelog
@chapter Changelog

This changelog only describes user-facing changes.

@menu
* Version 0.3.0 @emph{<2024-11-19 Tue>}: Version 030 @emph{<2024-11-19 Tue>}. 
* Version 0.2.2 released on @emph{<2024-07-05 Fri>}: Version 022 released on @emph{<2024-07-05 Fri>}. 
@end menu

@node Version 030 @emph{<2024-11-19 Tue>}
@section Version 0.3.0 @emph{<2024-11-19 Tue>}

@itemize
@item
Deprecate Nael.
@end itemize

@node Version 022 released on @emph{<2024-07-05 Fri>}
@section Version 0.2.2 released on @emph{<2024-07-05 Fri>}

@itemize
@item
Fix link to homepage (@uref{https://codeberg.org/mekeor/nael}).
@item
Add links to Nael customization group.
@item
Support Imenu even if Eglot is not enabled.
@item
When customizing Nael mode hook, suggest functions.
@end itemize

@bye
