\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename nael.info
@settitle Nael – Emacs major mode for Lean
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@dircategory Emacs misc features
@direntry
* Nael: (nael).         Major mode for Lean.
@end direntry

@finalout
@titlepage
@title Nael – Emacs major mode for Lean
@author Mekeor Melire
@end titlepage

@ifnottex
@node Top
@top Nael – Emacs major mode for Lean

Nael is a package for @uref{https://www.gnu.org/software/emacs/, GNU Emacs} that provides a major mode for @uref{https://lean-lang.org/, Lean}
language. “Nael” reversed is “Lean” and ends in “el” as in Emacs-Lisp.

@end ifnottex

@menu
* Installation::
* Status::
* License::
* Changelog::

@detailmenu
--- The Detailed Node Listing ---

Changelog

* Version 0.3.0 released on @emph{<2024-11-19 Tue>}: Version 030 released on @emph{<2024-11-19 Tue>}. 
* Version 0.2.2 released on @emph{<2024-07-05 Fri>}: Version 022 released on @emph{<2024-07-05 Fri>}. 

@end detailmenu
@end menu

@node Installation
@chapter Installation

After cloning Nael's Git repository, adopt following in your Emacs
user initialization file:

@lisp
;;;; Load

(add-to-list 'load-path "~/path/to/nael")
(require 'nael)

;;;; Optional: Configure

(defun my-nael-setup ()
  (interactive)
  ;; Enable Emacs' built-in `TeX' input-method.  Alternatively, you
  ;; could install the external `unicode-math-input' package and
  ;; use the `unicode-math' input-method.
  (set-input-method "TeX")
  ;; Enable Emacs' built-in LSP-client Eglot.
  (eglot-ensure))

(add-hook 'nael-mode-hook #'my-nael-setup)

;; Nael buffer-locally sets `compile-command' to "lake build".
(keymap-set nael-mode-map "C-c C-c" #'project-compile)

;; Find out how to type the character at point in the current
;; input-method.
(keymap-set nael-mode-map "C-c C-k" #'quail-show-key)
@end lisp

@node Status
@chapter Status

Nael is experimental and it's uncertain if it'll be maintained in
future.

@node License
@chapter License

Effectively, Nael is licensed under GPLv3.  To be more precise, some
parts are under weak Apache-2.0 license whereas other parts are under
the stricter GPLv3.

@node Changelog
@chapter Changelog

This changelog only describes user-facing changes.

@menu
* Version 0.3.0 released on @emph{<2024-11-19 Tue>}: Version 030 released on @emph{<2024-11-19 Tue>}. 
* Version 0.2.2 released on @emph{<2024-07-05 Fri>}: Version 022 released on @emph{<2024-07-05 Fri>}. 
@end menu

@node Version 030 released on @emph{<2024-11-19 Tue>}
@section Version 0.3.0 released on @emph{<2024-11-19 Tue>}

@itemize
@item
Deprecate Nael in favor of working on
@uref{https://github.com/leanprover-community/lean4-mode, leanprover-community/lean4-mode}.
@end itemize

@node Version 022 released on @emph{<2024-07-05 Fri>}
@section Version 0.2.2 released on @emph{<2024-07-05 Fri>}

@itemize
@item
Fix link to @uref{https://codeberg.org/mekeor/nael, homepage}.
@item
Add links to Nael customization group.
@item
Support Imenu even if Eglot is not enabled.
@item
When customizing Nael mode hook, suggest functions.
@end itemize

@bye
