#+title:                Nael – An Emacs major mode for Lean
#+author:               Mekeor Melire
#+language:             en
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_desc:     Major mode for Lean.
#+texinfo_dir_title:    Nael: (nael).
#+export_file_name:     nael.texi
#+options:              toc:nil

Nael is a package for [[https://www.gnu.org/software/emacs/][GNU Emacs]] that provides a major-mode for the
[[https://lean-lang.org/][Lean]] language. “Nael” reversed is “Lean” and ends in “el” as in
Emacs-Lisp.

* Installation

After cloning Nael's Git repository, adopt following in your Emacs
user initialization file:

#+begin_src elisp
;;;; Load

(add-to-list 'load-path "~/path/to/nael")
(require 'nael)

;; Configure (opional)

(defun my-nael-setup ()
  (interactive)
  ;; Enable Emacs' built-in `TeX' input-method.  Alternatively, you
  ;; could install the external `unicode-math-input' package and
  ;; use the `unicode-math' input-method.
  (set-input-method "TeX")
  ;; Enable Emacs' built-in LSP-client Eglot.
  (eglot-ensure))

(add-hook 'nael-mode-hook #'my-nael-setup)

;; Nael buffer-locally sets `compile-command' to "lake build".
(keymap-set nael-mode-map "C-c C-c" #'project-compile)

;; Find out how to type the character at point in the current
;; input-method.
(keymap-set nael-mode-map "C-c C-k" #'quail-show-key)
#+end_src

* Status

The future of Nael is uncertain. It hasn't been maintained for a while
but might be maintained in future.

* License

This program is based on Lean4-Mode which is licensed under
Apache-2.0.  Additions and modifications made within this repository
are licensed under GNU General Public License version 3 or later.

* History

1. /Microsoft/ et al. developed [[https://github.com/leanprover-community/lean4-mode][Lean4-Mode]] based on [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]].
2. /Richard Copley/ developed a [[https://github.com/bustercopley/lean4-mode][fork]] based on Emacs' built-in [[https://www.gnu.org/software/emacs/manual/html_node/eglot/][Eglot]].
3. /Mekeor Melire/ developed Nael, a fork based on Richard Copley's
   fork, that heavily uses Emacs' built-in facilities like Eglot,
   ElDoc and Project.

* Comparison

- Nael does not depend on third-party lsp-mode.  Instead, you can
  optionally use Nael together with Emacs' built-in LSP-client Eglot.
- Nael does not offer any special buffer for information on the
  current goal etc.  Instead, Nael introduces two ElDoc documentation
  functions which will show up in the usual ElDoc buffer.
- Nael does not offer any special mechanism to detect the current
  project.  Instead, it introduces Lakefiles as Project root markers.
- Nael does not offer any special command to build the current
  project.  Instead, it configures the built-in ~project-compile~
  command to work.
- Nael does not offer any special input-method.  Instead, you may use
  the built-in =TeX= input-method or the =unicode-math= from the
  external [[https://github.com/astoff/unicode-math-input.el][unicode-math-input]] package.
- Nael does not solely use the Apache-2 license.  Instead, it is
  licensed partly under Apache-2, and partly under GPLv3+.
  Altogether, you can treat Nael as if it was under GPLv3+ since
  that's the stricter license.

* Changelog

This changelog only describes user-facing changes.

** Version 0.3.0 released on <2024-11-19 Tue>

- Deprecate Nael.

** Version 0.2.2 released on <2024-07-05 Fri>

- Fix link to [[https://codeberg.org/mekeor/nael][homepage]].
- Add links to Nael customization group.
- Support Imenu even if Eglot is not enabled.
- When customizing Nael mode hook, suggest functions.

* Roadmap :noexport:

- Extract support for Eglot into a separate minor mode and file.
- Support lsp-mode along Eglot.
- Autogenerate abbrev table from Lean4 VSCode plugin sources.
- Consider Emacs' built-in SMIE for indentation.
- Consider setting variables:
  - ~comment-quote-nested~
  - ~prettify-symbols-alist~
  - ~outline-regexp~
  - ~add-log-current-defun-function~
  - ~paragraph-separate~
  - ~electric-indent-chars~
  - ~electric-layout-rules~
- Introduce some customizable user-options regarding how goals and
  term-goals are displayed in the ElDoc buffer and how they are
  echoed.
- Check if we need to handle LSP code-actions in a special way, just
  like upstream.
- Check if we should to disable =workspace/didChangeWatchedFiles= just
  like upstream.
- Check if it's okay for a package to modify the
  ~project-vc-extra-root-markers~ variable (or if it is rather meant
  to be modified by users only).
- Support fontification via semantic tokens from language server:
  https://codeberg.org/eownerdead/eglot-semantic-tokens
  https://codeberg.org/harald/eglot-semtok
  https://github.com/joaotavora/eglot/pull/839
