#+title:                Nael – Emacs major mode for Lean
#+author:               Mekeor Melire
#+language:             en
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_desc:     Major mode for Lean.
#+texinfo_dir_title:    Nael: (nael).
#+export_file_name:     nael.texi
#+options:              toc:nil

Nael is a package for [[https://www.gnu.org/software/emacs/][GNU Emacs]] that provides a major mode for [[https://lean-lang.org/][Lean]]
language. “Nael” reversed is “Lean” and ends in “el” as in Emacs-Lisp.

* Installation

After cloning Nael's Git repository, adopt following in your Emacs
user initialization file:

#+begin_src elisp
;;;; Load

(add-to-list 'load-path "~/path/to/nael")
(require 'nael)

;;;; Optional: Configure

(defun my-nael-setup ()
  (interactive)
  ;; Enable Emacs' built-in `TeX' input-method.  Alternatively, you
  ;; could install the external `unicode-math-input' package and
  ;; use the `unicode-math' input-method.
  (set-input-method "TeX")
  ;; Enable Emacs' built-in LSP-client Eglot.
  (eglot-ensure))

(add-hook 'nael-mode-hook #'my-nael-setup)

;; Nael buffer-locally sets `compile-command' to "lake build".
(keymap-set nael-mode-map "C-c C-c" #'project-compile)

;; Find out how to type the character at point in the current
;; input-method.
(keymap-set nael-mode-map "C-c C-k" #'quail-show-key)
#+end_src

* Status

Nael is experimental and it's uncertain if it'll be maintained in
future.

* License

Effectively, Nael is licensed under GPLv3.  To be more precise, some
parts are under weak Apache-2.0 license whereas other parts are under
the stricter GPLv3.

* Changelog

This changelog only describes user-facing changes.

** Version 0.3.0 released on <2024-11-19 Tue>

- Deprecate Nael in favor of working on
  [[https://github.com/leanprover-community/lean4-mode][leanprover-community/lean4-mode]].

** Version 0.2.2 released on <2024-07-05 Fri>

- Fix link to [[https://codeberg.org/mekeor/nael][homepage]].
- Add links to Nael customization group.
- Support Imenu even if Eglot is not enabled.
- When customizing Nael mode hook, suggest functions.

* Roadmap :noexport:

- Extract support for Eglot into a separate minor mode and file.
- Support lsp-mode along Eglot.
- Autogenerate abbrev table from Lean4 VSCode plugin sources.
- Consider Emacs' built-in SMIE for indentation.
- Consider setting variables:
  - ~comment-quote-nested~
  - ~prettify-symbols-alist~
  - ~outline-regexp~
  - ~add-log-current-defun-function~
  - ~paragraph-separate~
  - ~electric-indent-chars~
  - ~electric-layout-rules~
- Introduce some customizable user-options regarding how goals and
  term-goals are displayed in the ElDoc buffer and how they are
  echoed.
- Check if we need to handle LSP code-actions in a special way, just
  like upstream.
- Check if we should to disable =workspace/didChangeWatchedFiles= just
  like upstream.
- Check if it's okay for a package to modify the
  ~project-vc-extra-root-markers~ variable (or if it is rather meant
  to be modified by users only).
- Support fontification via semantic tokens from language server:
  https://codeberg.org/eownerdead/eglot-semantic-tokens
  https://codeberg.org/harald/eglot-semtok
  https://github.com/joaotavora/eglot/pull/839
