;;; nael-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from nael.el

(autoload 'nael-mode "nael" "\
Major mode for Lean.

\\{nael-mode-map}

(fn)" t)
(register-definition-prefixes "nael" '("nael-"))


;;; Generated autoloads from nael-abbrev.el

(register-definition-prefixes "nael-abbrev" '("nael-abbrev-"))


;;; Generated autoloads from nael-eglot.el

(autoload 'nael-eglot-init "nael-eglot" "\
Prepare `eglot' to work with `nael-mode'." t)
(register-definition-prefixes "nael-eglot" '("nael-eglot-"))


;;; Generated autoloads from nael-skeleton.el

(register-definition-prefixes "nael-skeleton" '("nael-skeleton-"))


;;; End of scraped data

(provide 'nael-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nael-autoloads.el ends here
