;;; nael-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from nael.el

(autoload 'nael-mode "nael" "\
Major mode for Lean.

\\{nael-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist (cons "\\.lean\\'" 'nael-mode))
(register-definition-prefixes "nael" '("nael-"))


;;; Generated autoloads from nael-abbrev.el

(autoload 'nael-abbrev-config "nael-abbrev" "\
Configure `abbrev-mode' for `nael-mode'.

Buffer-locally sets `local-abbrev-table' and adds `nael-abbrev-expand'
to `post-self-insert-hook' so that symbol-including abbreviations are
expanded whenever suitable characters are inserted.")
(register-definition-prefixes "nael-abbrev" '("nael-abbrev-"))


;;; Generated autoloads from nael-eglot.el

(autoload 'nael-eglot-managed "nael-eglot" "\
Buffer-locally set up ElDoc and Eglot for Nael.

Use ElDoc documentation strategy `compose' and add ElDoc documentation
functions for goal and term goal." t)
(autoload 'nael-eglot-server-initialized "nael-eglot" "\
Buffer-locally correct Eglot's expectations on Lean LSP server.

Since `lake serve' does not output anything, instruct Eglot to not wait
for any output.

(fn _)")
(register-definition-prefixes "nael-eglot" '("nael-eglot-"))


;;; Generated autoloads from nael-skeleton.el

(register-definition-prefixes "nael-skeleton" '("nael-skeleton-"))


;;; End of scraped data

(provide 'nael-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nael-autoloads.el ends here
