#+title: Nael — An Emacs major mode for Lean
#+author: Mekeor Melire
#+language: en
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_desc: Major mode for Lean.
#+texinfo_dir_title: Nael: (nael).
#+export_file_name: nael.texi
#+options: toc:nil

Nael is a set of packages extending [[https://www.gnu.org/software/emacs/][GNU Emacs]] for editing [[https://lean-lang.org][Lean]] sources.  It is a radically refactored fork of [[https://github.com/leanprover-community/lean4-mode][Lean4-Mode]] with focus on simplicity, modularity and integration into Emacs' core.  It's still at an early stage of development.

The ~nael~ package defines a major mode.  In a modular, unobtrusive way, it also defines simple and complex abbreviations per [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Abbrevs.html][Abbrev]] and [[https://www.gnu.org/software/emacs/manual/html_node/autotype/][Skeleton]] respectively.  It teaches Emacs' built-in [[https://microsoft.github.io/language-server-protocol/ Language Server Protocol][LSP]] client [[https://www.gnu.org/software/emacs/manual/html_node/eglot/][Eglot]] about [[https://github.com/leanprover/lean4/blob/master/src/Lean/Data/Lsp/Extra.lean][Lean-specific LSP-extensions]] and tells [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Programming-Language-Doc.html][ElDoc]] to display that information, similar to the “[[https://github.com/leanprover/vscode-lean4/blob/master/vscode-lean4/manual/manual.md#infoview][info view]]” in [[https://marketplace.visualstudio.com/items?itemName=leanprover.lean4][vscode-lean]] that many are familiar with.  For users who prefer the external package [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]] as LSP client over Eglot, there's the ~nael-lsp~ package.

* Installation

Nael's LSP-based features (via Eglot or lsp-mode), require Lean version 4 to be [[https://lean-lang.org/install/manual/][installed]].  If you want to use lsp-mode, you might need to install lsp-mode before ~nael-lsp~.

** Manual Installation

Clone the Git repository.  In your Emacs initialization file, add Nael to ~load-path~ and load it.

#+begin_src emacs-lisp
;; git clone https://codeberg.org/mekeor/nael ~/path/to/nael

(add-to-list 'load-path "~/path/to/nael/nael")
;; (add-to-list 'load-path "~/path/to/nael/nael-lsp")
;; (add-to-list 'load-path "~/path/to/nael/nael-markdown")

(require 'nael)
;; (require 'nael-lsp)
;; (require 'nael-markdown)
#+end_src

Instead of eagerly loading Nael, you can load ~nael-autoloads~ after building it:

#+begin_src emacs-lisp
;; cd ~/path/to/nael && ./build.el autoloads

(require 'nael-autoloads)
;; (require 'nael-lsp-autoloads)
;; (require 'nael-markdown-autoloads)
#+end_src

To make this readme available to Emacs as Info manual, point Emacs to it:

#+begin_src emacs-lisp
(require 'info)
(info-initialize)
(add-to-list 'Info-directory-list "~/path/to/nael/nael")
#+end_src

** Installation via ~package-vc~

Since version 29 from 2023, Emacs ships with ~package-vc~ which enables the built-in package manager ~package~ to install from version-controlled source repositories.  Keep in mind to regularly upgrade such packages with the command ~package-vc-upgrade~ or ~package-vc-upgrade-all~.  (And please ignore the warnings that arise when ~package-vc~ attempts to byte-compile all Elisp source files in the repository instead of just the package-specific ones.)

*** Installation via ~package-vc-selected-packages~

In your Emacs session, select packages per ~package-vc-selected-packages~ variable and install them with =M-x package-vc-install-selected-packages RET=.  Persist the package selection in your Emacs initialization file too.  ~package-vc~ will generate =nael-autoloads.el= automatically.  To lazy-load Nael, load the autoloads file.  For eager loading, load =nael.el=.

#+begin_src emacs-lisp
(require 'package-vc)

(setopt package-vc-selected-packages
        '((nael
           :url "https://codeberg.org/mekeor/nael.git"
           :doc "nael/README.org"
           :lisp-dir "nael")
          ;; (nael-lsp
          ;;  :url "https://codeberg.org/mekeor/nael.git"
          ;;  :lisp-dir "nael-lsp")
          ;; (nael-markdown
          ;;  :url "https://codeberg.org/mekeor/nael.git"
          ;;  :lisp-dir "nael-markdown")
          ))

(package-initialize)

;; Option 1, lazy loading:
(require 'nael-autoloads)
;; (require 'nael-lsp-autoloads)
;; (require 'nael-markdown-autoloads)

;; Option 2, eager loading:
(require 'nael)
;; (require 'nael-lsp)
;; (require 'nael-markdown)
#+end_src

*** Installation via ~use-package~ =:vc=

Since version 30 from 2025, Emacs' popular ~use-package~ macro supports a =:vc= keyword as interface to ~package-vc~.  (Because each package has autoload-cookies on relevant expressions, and because ~use-package~ will load each package's =*-autoloads.el= file that is generated at installation, you don't need to specify load-triggers like =:mode=.  I.e. lazy-loading should work out of the box.)

#+begin_src emacs-lisp
(use-package nael
  :vc ( :url "https://codeberg.org/mekeor/nael.git"
        :doc "nael/README.org"
        :lisp-dir "nael"))

;; (use-package nael-lsp
;;   :after nael
;;   :vc ( :url "https://codeberg.org/mekeor/nael.git"
;;         :lisp-dir "nael-lsp"))

;; (use-package nael-markdown
;;   :after markdown-mode
;;   :vc ( :url "https://codeberg.org/mekeor/nael.git"
;;         :lisp-dir "nael-markdown"))
#+end_src

* Usage

Language Server Protocol (LSP):

- =C-c C-e= (~eglot~) starts an LSP client.
- When ~nael-lsp~ is autoloaded: =C-c C-l= (~lsp~) starts an alternative LSP client.
- =C-h .= (~eldoc-doc-buffer~) displays the ElDoc documentation buffer showing tactic state and expected goal at point.

Abbreviations:

- =C-c C-a= (~abbrev-mode~) enables abbreviations.
- =C-c C-k= (~nael-abbrev-help~) echoes abbreviations that expand to the character at point, or, if active, to the selected region.

Emacs commands beyond Nael:

- =C-c C-c= (~project-compile~) suggests builds the current project, suggesting =lake build= as command.
- =M-g i= (~imenu~) jumps to an interactively chosen definition in current buffer.
- =M-;= (~comment-dwim~) toggles the active region as comment or, if no region is active, creates a comment at end of line.
- =M-q= (~prog-fill-reindent-defun~) fills the string- or comment-paragraph at point, or reindents the point-surrounding code.

* Configuration

For key bindings, customize ~nael-mode-map~.  To automatically enable features (e.g. abbreviations, Eglot or lsp-mode) when Nael is started, customize ~nael-mode-hook~.  Here's an example:

#+begin_src emacs-lisp
(add-hook 'nael-mode-hook #'abbrev-mode)
(add-hook 'nael-mode-hook #'eglot-ensure)
#+end_src

Nael's Abbrev tables use the =:regexp= property which is [[https://github.com/minad/cape/discussions/158#discussioncomment-14687758][incompatible]] with [[https://github.com/company-mode/company-mode][Company]]'s ~company-abbrev~ and [[https://github.com/minad/cape][Cape]]'s ~cape-abbrev~.  Instead, Nael supports completion-at-point natively via ~nael-abbrev-capf~.  This CAPF is buffer-locally added to ~completion-at-point-functions~ whenever Abbrev mode is enabled inside Nael.  To ditch this feature, set the ~nael-abbrev-capf~ variable to =nil=.

* Changelog

** Version 0.6.2 from 2025-11-30

- Re-add readme as .texi and .info to repository because Nael might soon be added to Melpa which won't build Info manuals itself.

** Version 0.6.0 from 2025-11-30

- Remove .texi, .info, and -autoloads.el files from repository.  Thus, don't load autoloads-files from other Elisp sources.  This makes Nael compatible with package-vc.
- build.el: Only build files/targets passed as command-line arguments.  Valid arguments are abbreviations, autoloads, compile, info and root-readme.
- dir-locals.el: Remove an assignment of a non-core Emacs variable which lead to Emacs asking for confirmation.
- README: Provide installation instructions via package-vc-selected-packages and use-package :vc.
- Add several autoload-cookies.  This allows for simpler use-package expressions.
- README: Add changelog chapter.
- nael, nael-abbrev:
  - Rename nael-abbrev-table-only-singletons to nael-abbrev-singleton-table.
  - Rename nael-abbrev-table-only-skeletons to nael-abbrev-skeleton-table.

* License and Maintenance

Nael is effectively licensed under GNU GPL version 3 only.  More precisely, it is licensed under Apache-2.0 and sublicensed under GPL-3.0.

Nael is maintained by /Mekeor Melire/ ([[mailto:mekeor@posteo.de][mekeor@posteo.de]]) on [[https://codeberg.org/mekeor/nael][Codeberg]].
