#+title: Nael — An Emacs major mode for Lean
#+author: Mekeor Melire
#+language: en
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_desc: Major mode for Lean.
#+texinfo_dir_title: Nael: (nael).
#+export_file_name: nael.texi
#+options: toc:nil

=nael=, =nael-lsp= and =nael-markdown= are packages extending [[https://www.gnu.org/software/emacs/][GNU Emacs]] for editing [[https://lean-lang.org][Lean]] sources.  Nael is a radically refactored fork of [[https://github.com/leanprover-community/lean4-mode][Lean4-Mode]] with focus on simplicity, modularity and integration into Emacs' core.  It's still at an early stage of development.

The =nael= package defines the major mode.  In a modular, unobtrusive way, it defines simple and complex abbreviations per [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Abbrevs.html][Abbrev]] and [[https://www.gnu.org/software/emacs/manual/html_node/autotype/][Skeleton]] respectively.  It teaches Emacs' built-in [[https://microsoft.github.io/language-server-protocol/ Language Server Protocol][LSP]] client [[https://www.gnu.org/software/emacs/manual/html_node/eglot/][Eglot]] about [[https://github.com/leanprover/lean4/blob/master/src/Lean/Data/Lsp/Extra.lean][Lean-specific LSP-extensions]] and tells [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Programming-Language-Doc.html][ElDoc]] to display that information, similar to the “[[https://github.com/leanprover/vscode-lean4/blob/master/vscode-lean4/manual/manual.md#infoview][info view]]” in [[https://marketplace.visualstudio.com/items?itemName=leanprover.lean4][vscode-lean]] that many are familiar with.

The =nael-lsp= package depends on [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]], an external package providing another LSP client, and teaches it about the Lean-specific LSP-extensions.

* Installation

*[[https://lean-lang.org/install/manual/][Install]] Lean* version 4.

** Via manual =git clone= and ~load-path~

Clone the Git repository.

#+begin_src shell
git clone https://codeberg.org/mekeor/nael ~/path/to/nael
#+end_src

In your Emacs initialization file, add entries to the ~load-path~ variable:

#+begin_src emacs-lisp
(add-to-list 'load-path "~/path/to/nael/nael")
;; (add-to-list 'load-path "~/path/to/nael/nael-lsp")
;; (add-to-list 'load-path "~/path/to/nael/nael-markdown")
#+end_src

And load Nael:

#+begin_src emacs-lisp
(require 'nael)
;; (require 'nael-lsp)
;; (require 'nael-markdown)
#+end_src

Optionally, configure Nael.

** Via ~use-package~ and =:vc=

#+begin_src emacs-lisp
(use-package nael
  :vc ( :url "https://codeberg.org/mekeor/nael.git"
        :lisp-dir "nael"))
#+end_src

(Unfortunately, Emacs' built-in ~package-vc~ will byte-compile the Elisp source files of all packages inside Nael's Git repository. Please ignore the resulting compilation warnings.)

* Usage

Language Server Protocol (LSP):

- To start an LSP client automatically, configure =nael-mode-hook=.  To start one interactively, type =C-c C-e= (~eglot~), or, if you have installed =nael-lsp=, =C-c C-l= (~lsp~).

- =C-h .= (~eldoc-doc-buffer~) displays the ElDoc documentation buffer showing tactic state and expected goal at point.

Abbreviations:

- To enable abbreviations automatically, configure ~nael-mode-hook~.  To enable them interactively, type =C-c C-a= (~abbrev-mode~).

- =C-c C-k= (~nael-abbrev-help~) will tell you how the abbreviation for the active region or character at point.

- Note that Nael's Abbrev tables use the =:regexp= property which [[https://github.com/minad/cape/discussions/158#discussioncomment-14687758][is]] neither compatible with Company nor Cape.  For completion at point, =nael-abbrev= defines ~nael-abbrev-capf~ which is buffer-locally added to ~completion-at-point-functions~ whenever Abbrev mode is enabled inside Nael.  To ditch this CAPF, set the ~nael-abbrev-capf~ variable to =nil=.

Emacs commands beyond Nael:

- =C-c C-c= or equally =C-x p c= (~project-compile~) suggests =lake build= as command to build the current project.
- =M-g i= (~imenu~) jumps to a interactively chosen definition in current buffer.
- =M-;= (~comment-dwim~) will toggle active region as comment or, if no region is active, create a comment at end of line.
- =M-q= (~prog-fill-reindent-defun~) will fill the string- or comment-paragraph at point, or reindent the point-surrounding code.

* License and Maintenance

Nael is effectively licensed under GNU GPL version 3 only.  More precisely, it is licensed under Apache-2.0 and sublicensed under GPL-3.0.

Nael is maintained by /Mekeor Melire/ ([[mailto:mekeor@posteo.de][mekeor@posteo.de]]) on [[https://codeberg.org/mekeor/nael][Codeberg]].
